- README.md
Hey! Just created a list of CLI workshoppers. Hope it makes a good addition :) Cheers!
> Added awesome-workshopper

- README.md
`https://github.com/dhamaniasad/awesome-linux/` has been merged with `https://github.com/aleksandar-todorovic/awesome-linux/`
> Update awesome-linux link

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jnv/lists/39)
> Add awesome-purescript

- README.md
Added the [Codeface repo](https://github.com/chrissimpkins/codeface) link and brief description to the README file.
> add Codeface link

- README.md
> Removing missing library vkbansal/awesome

- README.md
> add GoBooks

- README.md
> Adds Awesome-ConservationTech

- README.md
Add https://github.com/igorbarinov/awesome-data-engineering
> Add awesome-data-engineering

- README.md
Add https://github.com/igorbarinov/awesome-bitcoin
> Add awesome-bitcoin

- README.md
Hello, this patch adds a curated list of awesome programming, development, technical support and discussion channels, groups, communities and similar resources.
Thanks for considering merging it to this repository.
> awesome-community repository

- README.md
Hello, this patch adds awesome-jquery list. Thanks for considering merging it.
> Awesome jquery

- README.md
https://github.com/ujjwalkarn/Machine-Learning-Tutorials
> Add Machine Learning Tutorials

- README.md
List: https://github.com/ungerts/awesome-bpm
> Add BPM awesomeness

- README.md
Added link of curated list of useful xcode plugin in awesome list, under alphabetical order 😊 .
> Added Useful Xcode Plugin

- README.md
Could you add @grabear's awesome-rshiny list? @jnv
> Add awesome-rshiny

- README.md
[https://github.com/lambtron/awesome-deku](https://github.com/lambtron/awesome-deku)
> Add awesome-deku

- README.md
https://github.com/mislavcimpersak/awesome-dev-fun
This is a list of funny, whimsical and mostly useless scripts/packages from which developers can get a good laugh.
> Add awesome-dev-fun

- README.md
Scalability, Availability, and Stability Design Patterns in Back-end Development.
> Add awesome-scalability

- README.md
Hi!
I created this list in June 2016, the list now contains +300 resources that are useful when programming with fonts. This repository received multiple PR by third parties and more and more people are using it now!
> Add awesome-typography

- README.md
Hey,
Do you mind to add my awesome list to your awesome list of lists?
Thanks :D
> Add link to the awesome python models list.

- README.md
Link: [interviews](https://github.com/kdn251/interviews)
> add interviews

- README.md
Hundreds of community detection (graph clustering) research papers with implementations.
https://github.com/benedekrozemberczki/awesome-community-detection
> Added Awesome Community Detection

- README.md
Added awesome graph embedding papers list -- each paper has a public implementation in the list. Learning from graphs at the graph level (molecule classification, fraudulent transaction detection).
> Added awesome graph embedding.

- README.md
Added awesome graph embedding papers list -- each paper has a public implementation in the list. Learning from nodes in a graph (user classification, link prediction).
> Add awesome-network-embedding.

- README.md
https://github.com/bcoe/awesome-cross-platform-nodejs
Libraries and resources related to writing Node.js that works on Windows, Mac, Linux and BSD, by @bcoe.
Why this matters: according to the [2018 Node.js user survey](https://nodejs.org/en/user-survey-report/#Primary-OS-Distro), 24% of Node.js developers use Windows locally and 41% use Mac. In production 85% use Linux and 1% use BSD.
> Add Cross-platform Node.js

- README.md
A curated list of gradient and adaptive boosting papers with implementations from the following conferences:
Machine learning
NeurIPS
ICML
ICLR
Computer vision
CVPR
ICCV
ECCV
Natural language processing
ACL
NAACL
EMNLP
Data Mining
KDD
ICDM
WWW
Artificial intelligence
AAAI
IJCAI
UAI
> Added repo on gradient boosting papers.

- README.md
A curated list of gradient and adaptive boosting papers with implementations from the following conferences:
Machine learning
NeurIPS
ICML
ICLR
Computer vision
CVPR
ICCV
ECCV
Natural language processing
ACL
NAACL
EMNLP
Data Mining
KDD
ICDM
WWW
Artificial intelligence
AAAI
IJCAI
UAI
> Added repo on fraud detection

- README.md
A curated list of decision, classification and regression tree research papers with implementations from the following conferences:
Machine learning
NeurIPS
ICML
ICLR
Computer vision
CVPR
ICCV
ECCV
Natural language processing
ACL
NAACL
EMNLP
Data
KDD
ICDM
SDM
PAKDD
PKDD/ECML
SIGIR
WWW
WSDM
Artificial intelligence
AAAI
AISTATS
ICANN
IJCAI
UAI
> Awesome decision tree papers

- README.md
A List of best Soundtracks to boost your Productivity and Focus
> Added ProjectSoundtracks

- README.md
https://github.com/iamakulov/awesome-webpack-perf
A curated list of webpack tools for web performance
> Add awesome-webpack-perf

- README.md
Added [awesome-hasura](https://github.com/aaronhayes/awesome-hasura) to the list.
> Add awesome-hasura

- README.md
List of satellite imagery datasets with annotations for computer vision and deep learning
> add awesome-satellite-imagery-datasets

- README.md
[awesome-blender](https://github.com/agmmnn/awesome-blender), list of Blender add-ons, tools, tutorials and resources.
> Add awesome-blender

- README.md
Added this repo for the conceptual understanding behind all machine learning algorithms. Other repos provide mostly code. This repo has concepts.
> Add machine-learning-algorithms

- README.md
https://github.com/andressoop/global-reports
> Add global-reports

- README.md
> Add curated lists of engineering culture & processes

- README.md
https://github.com/mjhea0/awesome-fastapi
Thanks!
> Add awesome-fastapi

- README.md
Add pshah123's list of lists, which contained some lists which were not in other lists of lists.
> Add pshah123's list of lists

- README.md
Add https://github.com/apis-list/apis-list
It is community maintained, human and machine readable list of Public APIs.
> Add apis-list/apis-list

- README.md
Hi,
Add https://github.com/mehdihadeli/awesome-dotnet-architecture
Add https://github.com/mehdihadeli/awesome-dotnet-core-education
Add https://github.com/mehdihadeli/awesome-dotnet-async
Thanks.
> Adding dotnet-core-education, awesome-dotnet-async, awesome-dotnet-architecture Lists

- README.md
I am requesting an addition of [`awesome-bitclout`](https://github.com/BarryMode/awesome-bitclout), a curated list of awesome BitClout things.
> Add awesome-bitclout

- README.md
https://github.com/imsky/awesome-manifestos - a list of software manifestos/principles like The Twelve-Factor App
> Add awesome-manifestos

- README.md
This PR introduces the [`remote-software-companies`](https://github.com/RemoteByDefault/remote-software-companies) repository to the list.
> Add `remote-software-companies`

- README.md
The [enedil/awesome-awesome-awesome-awesome-awesome-awesome](https://github.com/enedil/awesome-awesome-awesome-awesome-awesome-awesome) is not working any more : )
> Remove awesome-awesome-awesome-awesome-awesome-awesome-awesome

- README.md
Tools, research, papers and other projects related to password cracking and password security.
https://github.com/narkopolo/awesome-password-cracking
> Add awesome-password-cracking

- README.md
[awesome-Engineering-Team-Management](https://github.com/kdeldycke/awesome-engineering-team-management) will help you to understand and transition from software development to engineering management.
> Add awesome-engineering-team-management

- README.md
[awesome-IAM](https://github.com/kdeldycke/awesome-iam) is about user accounts, authentication and authorization.
> Add awesome-iam

- README.md
[Awesome-Billing](https://github.com/kdeldycke/awesome-billing) is a knowledge on implementing payments, invoicing, pricing, accounting, marketplace, fraud, and business intelligence.
> Add awesome-billing

- README.md
I removed character garbled between 'R' and 'esearch'.
> remove invalid character

- README.md
Link to the list: [https://github.com/svfat/awesome-celery](https://github.com/svfat/awesome-celery)
> Add awesome-celery

- README.md
https://github.com/agamm/awesome-developer-first
> Add awesome-developer-first

- README.md
https://github.com/scraly/developers-conferences-agenda
> Add developers-conferences-agenda

- README.md
added awesome-lite-websites by mdibaiee :)
> Add awesome-lite-websites

- README.md
https://github.com/fmerian/awesome-developer-first-directories
> Add awesome-developer-first-directories

- README.md
Adds https://github.com/beansource/awesome-orgs
> Add awesome-orgs

- README.md
https://github.com/workos/awesome-developer-experience
> Add awesome-developer-experience

- README.md
Adds awesome-plan9 by henesy :)
> Add awesome-plan9

- README.md
https://github.com/DukeLuo/awesome-awesome-prompts
An awesome list for collecting awesome lists related to prompt engineering.
> Add awesome-awesome-prompts 

- README.md
awesome-token-sale is deleted. Related #206
> remove awesome-token-sale

- README.md
https://github.com/refusado/awesome-css-only
> Add awesome-css-only

- README.md
awesome-dotnet-core-education is deleted.
> remove awesome-dotnet-core-education

- README.md
Odoo is popular Python ERP https://github.com/odoo/odoo
> Add awesome-odoo

- README.md
>  add [awesome-ChatGPT-with-AI] (https://github.com/xirong/Awesome-ChatGPT-with-AI)
